services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-pizzas
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - mongodb-pizzas:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongodb-pizzas:
    external: true