spring:
  application:
    name: clientes
  config:
    import: optional:file:.env[.properties]
  mongodb:
    host: localhost
    port: 27018
    database: ${MONGO_DATABASE}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: admin
server:
  port: 8080